export enum AppRoute {
  Main = "/",
  Movie = "/movie",
  Trends = "/trends",
  Favourites = "/favourites",
  Settings = "/settings",
  Auth = "/auth",
  SignUp = "/auth/signUp",
  SignUpSuccess = "/auth/signUpSuccess",
  ActivateAccount = "/auth/activate",
  SignIn = "/auth/signIn",
  Resert = "/auth/resert",
  NewPassword = "/auth/newPassword",
  NotFound = "/404",
}
