export const contriesList: Array<string> = [
  "United States",
  "United Kingdom",
  "Germany",
  "India",
  "Japan",
  "Belgium",
  "France",
  "Canada",
  "Netherlands",
  "Italy",
  "Australia",
  "Russia",
  "South Africa",
  "Romania",
  "China",
  "Hong Kong",
  "New Zealand",
  "Nigeria",
  "Israel",
  "Greece",
  "Philippines",
  "Mexico",
  "Latvia",
  "Spain",
  "Portugal",
  "Argentina",
  "Austria",
  "Indonesia",
  "Czech Republic",
  "Serbia",
  "Tunisia",
  "Cuba",
  "Sweden",
  "Norway",
  "Ukraine",
  "Iran",
  "Puerto Rico",
  "Finland",
  "Denmark",
];
export const reserveData = [
  {
    Title: "Death on the Nile",
    Year: "2022",
    Rated: "PG-13",
    Released: "11 Feb 2022",
    Runtime: "127 min",
    Genre: "Crime, Drama, Mystery",
    Director: "Kenneth Branagh",
    Writer: "Michael Green, Agatha Christie",
    Actors: "Tom Bateman, Annette Bening, Kenneth Branagh",
    Plot: "Belgian sleuth Hercule Poirot's vacation aboard a glamorous river steamer turns into a terrifying search for a murderer when a picture-perfect couple's idyllic honeymoon is tragically cut short. Set against an epic landscape of sweeping Egyptian desert vistas and the majestic Giza pyramids, this tale of unbridled passion and incapacitating jealousy features a cosmopolitan group of impeccably dressed travelers, and enough wicked twists and turns to leave audiences guessing until the final, shocking denouement.",
    Language: "English, French, German",
    Country: "United States, United Kingdom",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjI4ZTQ1OTYtNTI0Yi00M2EyLThiNjMtMzk1MmZlOWMyMDQwXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.3/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "62%",
      },
      {
        Source: "Metacritic",
        Value: "52/100",
      },
    ],
    Metascore: "52",
    imdbRating: "6.3",
    imdbVotes: "133,528",
    imdbID: "tt7657566",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$45,630,104",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Life and Death in the Warehouse",
    Year: "2022",
    Rated: "N/A",
    Released: "07 Mar 2022",
    Runtime: "59 min",
    Genre: "Drama",
    Director: "Aysha Rafaele, Joseph Bullman",
    Writer: "Helen Black, Joseph Bullman",
    Actors: "Aimee-Ffion Edwards, Poppy Lee Friar, Craig Parkinson",
    Plot: 'In a desperate attempt to keep her new job at a Welsh warehouse, Megan presses a pregnant colleague to get her "pick rate" up, putting her and her fetus at risk.',
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2RiNjc2NjQtYjAzNi00MzMyLTg2NjctN2VkNTllZmM0ZDVlXkEyXkFqcGdeQXVyMTQ5MTkzOTg2._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.4",
    imdbVotes: "321",
    imdbID: "tt17519342",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Death Count",
    Year: "2022",
    Rated: "N/A",
    Released: "19 Jul 2022",
    Runtime: "81 min",
    Genre: "Horror",
    Director: "Michael Su",
    Writer: "Rolfe Kanefsky, Michael Merino",
    Actors: "Costas Mandylor, Michael Madsen, Robert LaSardo",
    Plot: "Strangers awaken in individual holding cells with no memory of how they arrived. They realize if they don't acquire enough online \"likes\" in a timely manner, they'll die horribly at the hands of a sinister executioner.",
    Language: "N/A",
    Country: "United States",
    Awards: "1 win & 1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTI1NjA5NDItYThlNi00NWRiLWI4NzItOWU0OTYyOGNkMzhlXkEyXkFqcGdeQXVyNTI4MTg4Mw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "4.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "4.3",
    imdbVotes: "1,305",
    imdbID: "tt12338246",
    Type: "movie",
    DVD: "19 Jul 2022",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Our Flag Means Death",
    Year: "2022–",
    Rated: "TV-MA",
    Released: "03 Mar 2022",
    Runtime: "N/A",
    Genre: "Action, Adventure, Biography",
    Director: "N/A",
    Writer: "David Jenkins",
    Actors: "Rhys Darby, Joel Fry, Samson Kayo",
    Plot: "Based on the true adventures of 18th century would-be pirate, Stede Bonnet (Rhys Darby). After trading in the seemingly charmed life of a gentleman for one of a swashbuckling buccaneer, Stede becomes captain of the pirate ship Revenge. Struggling to earn the respect of his potentially mutinous crew, Stede's fortunes change after a fateful run-in with the infamous Captain Blackbeard. Stede and crew attempt to get their ship together and survive life on the high seas.",
    Language: "English",
    Country: "United States",
    Awards: "11 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTNiYjcxM2UtOGE3NC00OGU1LTk2ZTgtYTYxODFiMDQzYjI1XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.8",
    imdbVotes: "24,117",
    imdbID: "tt11000902",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Life After Death with Tyler Henry",
    Year: "2022–",
    Rated: "TV-MA",
    Released: "11 Mar 2022",
    Runtime: "N/A",
    Genre: "Reality-TV",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Theresa Koelewyn, Tyler Henry, Constantinos Isaias",
    Plot: "After years of being Hollywood's go-to medium, Tyler heads out across the country to offer readings to as many of the people on his waiting list as he can, bringing them the hope, healing and closure they are seeking.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2Y2MDhlNmItZTFjMy00YWI4LTkwZGQtNWQ3ODU4ZGVmYzU2XkEyXkFqcGdeQXVyMTY2Nzk0NDY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.9",
    imdbVotes: "979",
    imdbID: "tt18217272",
    Type: "series",
    totalSeasons: "N/A",
    Response: "True",
  },
  {
    Title: "Death Bed Game",
    Year: "2022",
    Rated: "N/A",
    Released: "12 Feb 2022",
    Runtime: "32 min",
    Genre: "Short, Action, Horror",
    Director: "Rui Constantino",
    Writer: "Rui Constantino",
    Actors: "Rui Constantino, Miguel D. Dias",
    Plot: "A man awakens in a room, in a strange bed, when he tries to get out, he can't because there's traps everywhere, if he leaves the bed, he dies, then he receives a call from Dr. Death, telling him that the truth will set him free, now he must find a way to escape this nightmare.",
    Language: "English",
    Country: "Portugal",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjNmNTA2ZjgtMWVlZi00YzVkLWI1NzItMTgzMjJlMGExMDg4XkEyXkFqcGdeQXVyMTgxOTU2MTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.2",
    imdbVotes: "211",
    imdbID: "tt15485388",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Death Hunt",
    Year: "2022",
    Rated: "N/A",
    Released: "10 Mar 2022",
    Runtime: "92 min",
    Genre: "Action, Thriller",
    Director: "Neil Mackay",
    Writer: "Neil Mackay, Sean McAulay",
    Actors: "Rick Amsbury, Michael Coughlan, Mason Cromwell",
    Plot: "A land developer and his girlfriend are hunted on a remote island for sport by three deranged locals.",
    Language: "English",
    Country: "Canada",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjc0MDUzZTItYzJkNi00MzhlLTk1YTUtYzE1NDZjZGNlYzM3XkEyXkFqcGdeQXVyMjEwNjUxOA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.6",
    imdbVotes: "208",
    imdbID: "tt14100830",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Choosing Death: The Legacy of Roe",
    Year: "2022",
    Rated: "N/A",
    Released: "13 May 2022",
    Runtime: "45 min",
    Genre: "Documentary",
    Director: "Ian Reid",
    Writer: "Ian Reid",
    Actors: "Christina Bennett, Terrisa Bukovinac, Claire Culwell",
    Plot: "For half a century, the abortion industry has propped itself up on legal perversion, political corruption, and medical malpractice. In its new original documentary, The Daily Wire takes a wrecking ball to the four core fallacies s...",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTIzY2ZjZjQtMjNhZi00MTQ2LWEwZTEtMzc1ZGQ2ZTI5M2Y5XkEyXkFqcGdeQXVyNzExMzc0MDg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "110",
    imdbID: "tt20230982",
    Type: "movie",
    DVD: "13 May 2022",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Death of April",
    Year: "2022",
    Rated: "Not Rated",
    Released: "23 Mar 2022",
    Runtime: "90 min",
    Genre: "Horror, Mystery",
    Director: "Ruben Rodriguez",
    Writer: "Ruben Rodriguez",
    Actors: "Amy Rutledge, Katarina Hughes, Stephanie Domini",
    Plot: "Meagan Mullen, freshly moved in her new home, keeps in touch with her friends and family through a video blog. As her entries (and her life) become more complex and emotional, strange things begin to happen in her room: and the camera captures all of it. Told primarily from the point of view of an ordinary wireless webcam, The Death of April documents the unsettling activity in an otherwise average girl's bedroom - and the mysteries that surround it.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmRjMjc4YWItZDRhMS00YWYxLWIwYWEtODc4YTQ4NWY5ODI4XkEyXkFqcGdeQXVyMTU0ODI1Nzg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "4.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "4.5",
    imdbVotes: "210",
    imdbID: "tt2229103",
    Type: "movie",
    DVD: "13 Mar 2017",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
